{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "172d0289-fca8-4e12-a589-c328f27fa050",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from tensorflow.keras.models import load_model\n",
    "import pickle # 用來載入你的 scaler\n",
    "\n",
    "# 1. 網頁標題與選單\n",
    "st.set_page_config(page_title=\"白馬村滑雪天氣AI助理\", page_icon=\"❄️\")\n",
    "st.title(\"❄️ 白馬村滑雪天氣AI助理\")\n",
    "st.write(\"透過LSTM深度學習模型預測最佳滑雪時機\")\n",
    "\n",
    "# 2. 側邊欄：使用者輸入\n",
    "st.sidebar.header(\"請選擇您的旅遊期間:\")\n",
    "start_date = st.sidebar.date_input(\"開始日期:\")\n",
    "end_date = st.sidebar.date_input(\"結束日期:\")\n",
    "\n",
    "# 3. 載入模型與工具 (這部分建議先在 Colab 儲存好)\n",
    "# @st.cache_resource 確保模型只會載入一次，節省手機開啟時間\n",
    "@st.cache_resource\n",
    "def load_ai_assets():\n",
    "    model = load_model('my_lstm_model.h5')\n",
    "    with open('scaler.pkl', 'rb') as f:\n",
    "        scaler = pickle.load(f)\n",
    "    return model, scaler\n",
    "\n",
    "# 4. 核心邏輯 (將你之前的 get_ski_recommendation 放進來)\n",
    "def get_ski_recommendation(start_date_str, end_date_str, model, scaler, df, window_size=7):\n",
    "    # 1. 時間格式轉換\n",
    "    start_date = pd.to_datetime(start_date_str)\n",
    "    end_date = pd.to_datetime(end_date_str)\n",
    "    last_date = df['Date'].max()\n",
    "    \n",
    "    # 2. 定義特徵欄位 (必須是訓練時的 9 個)\n",
    "    features_cols = ['tavg', 'tmax', 'tmin', 'prcp', 'snowf', 'snowdmax', 'sunhour', 'month_sin', 'month_cos']\n",
    "    \n",
    "    # 3. 準備儲存結果的清單\n",
    "    predictions_list = []\n",
    "\n",
    "    # 4. 判斷區間落在「歷史」還是「未來」\n",
    "    # 如果區間完全在歷史內，直接從 df 抓\n",
    "    if end_date <= last_date:\n",
    "        relevant_df = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)]\n",
    "        for _, row in relevant_df.iterrows():\n",
    "            predictions_list.append({\n",
    "                'date': row['Date'],\n",
    "                'tavg': row['tavg'], 'tmax': row['tmax'], 'tmin': row['tmin'],\n",
    "                'snowf': row['snowf'], 'snowdmax': row['snowf'] # 歷史資料可能叫不同名\n",
    "            })\n",
    "    else:\n",
    "        # 如果包含未來，執行 LSTM 遞迴預測\n",
    "        days_to_predict = (end_date - last_date).days\n",
    "        \n",
    "        # 準備最後 window_size 天的資料作為啟動種子\n",
    "        last_data_raw = df[features_cols].tail(window_size).fillna(0).values\n",
    "        current_batch = scaler.transform(last_data_raw).reshape(1, window_size, 9)\n",
    "\n",
    "        for i in range(days_to_predict):\n",
    "            # 模型輸出 5 個值: [tavg, tmax, tmin, snowf, snowdmax]\n",
    "            pred = model.predict(current_batch, verbose=0)[0]\n",
    "            curr_date = last_date + pd.Timedelta(days=i+1)\n",
    "\n",
    "            # 如果這天在遊客要求的區間內，則還原並記錄\n",
    "            if start_date <= curr_date <= end_date:\n",
    "                dummy = np.zeros((1, 9))\n",
    "                dummy[0, 0:3] = pred[0:3] # tavg, tmax, tmin\n",
    "                dummy[0, 4:6] = pred[3:5] # snowf, snowdmax\n",
    "                res = scaler.inverse_transform(dummy)[0]\n",
    "                \n",
    "                predictions_list.append({\n",
    "                    'date': curr_date,\n",
    "                    'tavg': res[0], 'tmax': res[1], 'tmin': res[2],\n",
    "                    'snowf': res[4], 'snowdmax': res[5]\n",
    "                })\n",
    "\n",
    "            # 更新下一天的輸入 (維持 9 特徵)\n",
    "            m_sin = np.sin(2 * np.pi * curr_date.month / 12)\n",
    "            m_cos = np.cos(2 * np.pi * curr_date.month / 12)\n",
    "            # 構造 [tavg, tmax, tmin, prcp(0), snowf, snowdmax, sunhour(0.5), m_sin, m_cos]\n",
    "            new_entry = np.array([pred[0], pred[1], pred[2], 0, pred[3], pred[4], 0.5, m_sin, m_cos]).reshape(1, 1, 9)\n",
    "            current_batch = np.append(current_batch[:, 1:, :], new_entry, axis=1)\n",
    "\n",
    "    # 5. 評分與星星轉化邏輯 (延用之前的邏輯)\n",
    "# 5. 評分與星星轉化邏輯\n",
    "    final_scores = []\n",
    "    for day in predictions_list:\n",
    "        score = 0\n",
    "        score += day['snowdmax'] * 1.0  # 積雪深度分\n",
    "        if day['snowf'] > 2 and day['tmax'] < 0: \n",
    "            score += 30 # 粉雪分\n",
    "        if day['tmax'] > 3: \n",
    "            score -= 20 # 融雪扣分\n",
    "\n",
    "        # 這裡要確保所有的縮進 (Indentation) 都對齊\n",
    "        star_count = 1\n",
    "        if score >= 80: star_count = 5\n",
    "        elif score >= 50: star_count = 4\n",
    "        elif score >= 20: star_count = 3\n",
    "        elif score > 0: star_count = 2\n",
    "\n",
    "        # --- 關鍵修正區塊 ---\n",
    "        final_scores.append({\n",
    "            'date': day['date'],\n",
    "            'score': score,\n",
    "            'info': day,\n",
    "            'stars': \"⭐\" * star_count + \"☆\" * (5 - star_count),\n",
    "            'tips': get_travel_tips(star_count, day) # 注意這行要跟上面的對齊\n",
    "        })\n",
    "    # ------------------\n",
    "\n",
    "    if not final_scores:\n",
    "        return None, []\n",
    "\n",
    "    best_day = max(final_scores, key=lambda x: x['score'])\n",
    "    return best_day, final_scores\n",
    "\n",
    "\n",
    "\n",
    "# ------------------------------------------------------\n",
    "if st.sidebar.button(\"開始AI預測\"):\n",
    "    with st.spinner('AI正在計算雪況中...'):\n",
    "        # 這裡呼叫你之前寫好的函式\n",
    "        best_day, all_results = get_ski_recommendation(str(start_date), str(end_date), model, scaler, df)\n",
    "        \n",
    "        # 顯示最佳日期 (星星與小撇步)\n",
    "        st.success(f\"🏆 最佳推薦日：{best_day['date'].date()}\")\n",
    "        st.metric(\"推薦指數\", best_day['stars'])\n",
    "        st.info(f\"💡 教練建議：{best_day['tips']}\")\n",
    "        \n",
    "        # 顯示詳細數據表\n",
    "        st.subheader(\"📊 詳細預報數據\")\n",
    "        res_df = pd.DataFrame([r['info'] for r in all_results])\n",
    "        st.dataframe(res_df)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
